application: biblio-155121
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: ../client/build/index.html
  upload: ../client/build/index.html
- url: /app.css
  static_files: ../client/build/app.css
  upload: ../client/build/app.css
- url: /static
  static_dir: ../client/build/static
- url: /users.*
  script: _go_app
- url: /api.*
  script: _go_app

skip_files:
- ^client\/node_modules\/(?!build.*)
- ^.*node_modules(/.*)?
- ^.git/*
